Решение задач занятия 1
js-tasks-ru/jsbasic-20230629_egor-zhigarev pull request #2
Opened 2023-07-03 21:22 UTC by EgorZhi

2023-07-03 21:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-05 10:41 UTC, SinimaWath requested changes

2023-07-05 10:41 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
`return name !== null && name.length >= 4 && !name.includes(' ')` - if не нужен, так как операция возвращает true/false

2023-07-05 19:43 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-06 12:27 UTC, SinimaWath approved these changes

2023-07-06 12:27 UTC, merged